name: Release Rust Crate

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:
    inputs:
      version:
        description: The version to build

env:
  CARGO_TERM_COLOR: always

jobs:
  release:
    permissions:
      id-token: write

    runs-on: ubuntu-latest
    environment: release
    steps:
      - uses: actions/checkout@v6
        with:
          # The tag to build or the tag received by the tag event
          ref: ${{ github.event.inputs.version || github.ref }}
          persist-credentials: false

      - name: Install elan
        shell: bash
        run: |
          if [ "$RUNNER_OS" == "Windows" ]; then
            curl -sSfL https://github.com/leanprover/elan/releases/latest/download/elan-x86_64-pc-windows-msvc.zip -o elan.zip
            unzip elan.zip
            ./elan-init.exe -y --default-toolchain none
            rm -f elan-init.exe elan.zip
            echo "$USERPROFILE/.elan/bin" >> $GITHUB_PATH
          else
            echo "::group::Elan Installation Output"
            set -o pipefail
            curl https://raw.githubusercontent.com/leanprover/elan/master/elan-init.sh -sSf | sh -s -- -y --default-toolchain none
            rm -f elan-init
            echo "$HOME/.elan/bin" >> $GITHUB_PATH
            "$HOME"/.elan/bin/lean --version
            "$HOME"/.elan/bin/lake --version
            echo "::endgroup::"
          fi

      - uses: rust-lang/crates-io-auth-action@v1
        id: auth

      - name: Publish to crates.io
        run: |
          cargo publish -p leo3-macros-backend
          cargo publish -p leo3-macros
          cargo publish -p leo3-build-config
          cargo publish -p leo3-ffi
          cargo publish -p leo3
        env:
          CARGO_REGISTRY_TOKEN: ${{ steps.auth.outputs.token }}
